# Generated by Django 2.0.1 on 2018-01-21 01:32

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20180119_1455'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
                ('pune', django.db.models.manager.Manager()),
            ],
        ),
    ]
