# Generated by Django 2.0.1 on 2018-01-21 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datastrore',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
