# Generated by Django 2.0.1 on 2018-01-21 02:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_datastrore_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datastrore',
            old_name='date',
            new_name='update',
        ),
        migrations.AddField(
            model_name='datastrore',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
