# Generated by Django 2.0.1 on 2018-01-21 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20180121_0802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datastrore',
            old_name='name',
            new_name='post',
        ),
    ]
